### PR TITLE
Make compatible with CakePHP's AuthComponent

### PR DESCRIPTION
**Pull request by braindead1**
See issue: https://github.com/uzyn/cakephp-opauth/issues/6

### CODE REVIEW

**Comment by uzyn** [comment]
Thanks @braindead1.

I wasn't aware that CakePHP's SessionComponent also reads from `$_SESSION` with no problems.

This fix, however, causes some notices due to OpauthStrategy.php and some strategies still starting sessions, which is out of scope of this package.

```
Notice (8): A session had already been started - ignoring session_start() [APP/Plugin/Opauth/Strategy/Twitter/TwitterStrategy.php, line 90]
Notice (8): A session had already been started - ignoring session_start() [APP/Plugin/Opauth/Vendor/Opauth/lib/Opauth/OpauthStrategy.php, line 173]
```

**Comment by uzyn** [comment]
To avoid the notices, it would be great if we could allow Opauth and its strategies to also read/write to session that CakePHP has already started. As of now, I don't see any straight-forward way of passing CakePHP's session as `$_SESSION` to non-CakePHP libraries.

[This articles](http://bakery.cakephp.org/articles/brightball/2009/02/18/using-cake-sessions-outside-of-cake) describe how, but it involves modification at the app level, outside of the scope of this plugin.

As of now, I think the best way to switch the transport for Opauth to either POST or GET by adding this line to your `app/bootstrap.php`:

``` php
<?php
Configure::write('Opauth.callback_transport', 'post');
```

**Comment by uzyn** [comment]
@braindead1 Can you give the [latest plugin](https://github.com/downloads/uzyn/cakephp-opauth/Opauth-CakePHP-plugin-0.4.1.zip) a try? 

The session handling issue should be fixed.

**Comment by braindead1** [comment]
I'll give it a try hopefully tomorow.

Edit: I managed to check it today. With the newly uploaded sample app it is not possible to use AuthComponent. It's actually the same problem as before.

**Comment by uzyn** [comment]
I assume this is fixed. If it isn't, please reopen.

Thanks.

**Comment by rightawayai** [comment]
@uzyn this isn't fixed in the latest code, I had to use your work around in the bootstrap.php i.e., including 

Configure::write('Opauth.callback_transport', 'post');

**Comment by ramiel** [comment]
Latest version stopped working again.
The AuthComponent doesn't work due to Session write error.

**Comment by uzyn** [comment]
@ramiel Tell us more about the error please.

**Comment by ramiel** [comment]
@uzyn 
In this method, which is the callback for opauth

``` php
public function opauth_complete() {
        $uid = $this->data['auth']['uid'];
        $userSocial = $this->User->Social->find('first', array(
                'conditions' => array(
                    'Social.uid' => $uid
                )
            )
        );
        if($userSocial){
            $value = $this->Auth->login($userSocial['User']);
            debug($value);
        }else{
            debug('User not found');
        }   
    }
```

The manual login ($this->Auth->login($userSocial['User'])) always fails and it fails because when cake write in session nothing is wrote

**Pull request closed without merging**
