### PR TITLE
refactoring to use event instead of controllers in plugin

### PR DESCRIPTION
**Pull request by ceeram**
All thats now needed is define a single route in application routes, for instance

Router::connect('/auth/*', array('controller' => 'users', 'action' => 'opauth'));

### CODE REVIEW

**Comment by uzyn** [comment]
Thanks for the great work with the refactoring @ceeram 

Will check it out soon as I'll be out of town in a few hours time.

Just a quick question, any changes in usage?

**Comment by ceeram** [comment]
Not really, except all logic is now performed on same controller action, so callback url is now hardcoded to append Opauth.path  

so in the given example:
/auth/facebook maps to opauth() => Opauth->run() is executed and redirects to /auth/callback
/auth/callback maps to opauth() => Opauth callback handling is performed
within opauth() you can read $this->request->data

**Comment by uzyn** [comment]
Sorry for taking so long on this.

I feel that this should be on a separate development branch for the mean time for:
1. It requires CakeEvent, thus requiring CakePHP >= 2.1, whereas the current master supports CakePHP >= 2.0. 
   We can, however, eventually drop 2.0 support and have this upgraded as master.
2. Usage instructions do differ. README would need to be updated.

Personally, I also need to catch up with CakeEvent.

**Comment by fdeschenes** [comment]
@ceeram, it looks like the event handler doesn't is unable to read the session data set by Opauth.  When the `OpauthStrategy` class (from Opauth) starts a session in `OpauthStrategy::shipToCallback()`, it creates a session using PHP's default name which is set to PHPSESSID.

But when `CakeSession::_configureSession()` is called as a result of the `CakeSession::read()` call in `OpauthHandler::_readResponse()`, it sets up a session under the session name configure in `APP/core.php`, which defaults to CAKEPHP.

The only way I was able to use your modified version to work was by changing the `Session.cookie` setting in my `core.php` config file as follows:

``` php
Configure::write('Session', array(
    'cookie' => 'PHPSESSID',
    'defaults' => 'php'
));
```

I'm using a vanilla version of CakePHP 2.2.3 with no other plugins or library and a very basic user model.

**Comment by ceeram** [comment]
I didnt have to do such thing, i would need to look into it, but you should not be required to do that

**Comment by ceeram** [comment]
Currently opauth is going through a big rewrite for 1.0 this plugin isnt really required as the shipToCallback code will be removed. Closing this PR

**Pull request closed without merging**
